version: '3.7'
services:
  peer-base:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ID=peer-base
      - CORE_LOGGING_LEVEL=INFO
    volumes:
      - /var/run/:/host/var/run/
      - ../config:/etc/hyperledger/fabric
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
